---
swagger: '2.0'
info:
  version: 1.0.0
  title: REST API
  description: REST API for client
  termsOfService: http://swagger.io/terms/
  contact:
    email: ingeniero.miguelvargas@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:5000/
basePath: api/v1
tags:
  - name: Services
    description: User Services
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths: {}
